# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectclassifysecond',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='project.Project', verbose_name='项目列表'),
        ),
    ]
