# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20160323_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectclassifysecond',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='classify',
            field=models.ManyToManyField(blank=True, null=True, to='project.ProjectClassifySecond', verbose_name='类别'),
        ),
    ]
