# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20160323_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code_pattern',
            field=models.CharField(choices=[('open', '开源'), ('close', '闭源')], default='open', max_length=32, verbose_name='代码形式'),
        ),
        migrations.AddField(
            model_name='project',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '初级'), (2, '中级'), (3, '高级')], default=1, verbose_name='难度'),
        ),
        migrations.AddField(
            model_name='project',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='浏览数'),
        ),
        migrations.AddField(
            model_name='project',
            name='repository',
            field=models.CharField(choices=[('github', 'Github'), ('oschina', '开源中国'), ('coding', 'Coding'), ('personal', '个人仓库'), ('other', '其他')], default='github', max_length=32, verbose_name='托管方式'),
        ),
        migrations.AddField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='classify',
            field=models.ManyToManyField(to='project.ProjectClassifySecond', verbose_name='类别'),
        ),
    ]
