# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=200, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('insert_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'user',
            },
        ),
    ]
