# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User3rdAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(max_length=32, verbose_name='用户类型')),
                ('user_app_identity', models.CharField(max_length=128, verbose_name='应用内唯一id')),
                ('user_identity', models.CharField(max_length=128, verbose_name='第三方唯一id')),
                ('auth_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='授权时间')),
                ('auth_data', models.TextField(verbose_name='第三方返回的数据')),
            ],
            options={
                'db_table': 'user_3rd_authorization',
                'verbose_name': '用户第三方授权登录表',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('guid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('email_verified', models.BooleanField(default=False, verbose_name='邮箱验证确认状态')),
                ('mobile', models.CharField(max_length=16, verbose_name='手机号')),
                ('mobile_verified', models.BooleanField(default=False, verbose_name='手机号验证确认状态')),
                ('user_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('register_source', models.CharField(choices=[('web', '网站')], default='web', max_length=32, verbose_name='注册来源')),
                ('is_locked', models.BooleanField(default=False, verbose_name='锁定状态')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后一次登录时间')),
                ('login_fail_count', models.IntegerField(default=0, verbose_name='连续登录失败统计')),
            ],
            options={
                'db_table': 'user_account',
                'verbose_name': '用户表',
            },
        ),
        migrations.CreateModel(
            name='UserEmailVerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_type', models.CharField(choices=[('first_reg', '首次注册'), ('replace', '更换')], default='first_reg', max_length=32, verbose_name='验证类型')),
                ('code', models.CharField(max_length=1024, verbose_name='验证码')),
                ('valid_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='过期时间')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.UserAccount')),
            ],
            options={
                'db_table': 'user_email_verify_code',
                'verbose_name': '用户邮箱验证表',
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='昵称')),
                ('first_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='姓')),
                ('sex', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=32, null=True, verbose_name='性别')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='生日')),
                ('avatar', models.CharField(blank=True, max_length=1024, null=True, verbose_name='头像')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.UserAccount')),
            ],
            options={
                'db_table': 'user_information',
                'verbose_name': '用户信息表',
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登录时间')),
                ('login_source', models.CharField(choices=[('web', '网站')], default='web', max_length=32, verbose_name='登录来源')),
                ('login_result', models.BooleanField(default=True, verbose_name='登录结果状态')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.UserAccount')),
            ],
            options={
                'db_table': 'user_login_history',
                'verbose_name': '用户登录历史表',
            },
        ),
        migrations.CreateModel(
            name='UserNewEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.UserAccount')),
            ],
            options={
                'db_table': 'user_new_email',
                'verbose_name': '用户新邮箱表',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='user3rdauthorization',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.UserAccount'),
        ),
    ]
