# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0005_auto_20160326_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='education',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='学历'),
        ),
    ]
